### ISSUE TITLE
Leapfrog from K to N uses outdated openstack_hosts role

### ISSUE THREAD

**Issue by BjoernT** [rcbops/rpc-upgrades#368]
Due to

`ESC[0;31mfailed: [infra01] (item=[u'apparmor-utils', u'apt-transport-https', u'bridge-utils', u'build-essential', u'cgroup-lite', u'curl', u'dmeventd', u'dstat', u'ebtable
s', u'htop', u'iptables', u'irqbalance', u'libkmod-dev', u'libkmod2', u'linux-modules-extra-4.4.0-127-generic', u'lvm2', u'python-software-properties', u'python-dev', u'rsync', u
'rsyslog', u'sshpass', u'sysstat', u'time', u'vlan', u'wget']) => {"failed": true, "item": ["apparmor-utils", "apt-transport-https", "bridge-utils", "build-essential", "cgroup-li
te", "curl", "dmeventd", "dstat", "ebtables", "htop", "iptables", "irqbalance", "libkmod-dev", "libkmod2", "linux-modules-extra-4.4.0-127-generic", "lvm2", "python-software-prope
rties", "python-dev", "rsync", "rsyslog", "sshpass", "sysstat", "time", "vlan", "wget"], "msg": "No package matching 'linux-modules-extra-4.4.0-127-generic' is available"}ESC[0m
`
we should side load the newton eol role or a patched version where the package is not even requested at all due to os/kernel package name issues

https://github.com/openstack/openstack-ansible-openstack_hosts/blob/newton-eol/vars/ubuntu-14.04.yml

**Comment by BjoernT** [comment]
That seems to be an issue as we bootstrap ansible in a earlier newton version and then bootstrapping later into newton-eol

**Comment by antonym** [comment]
I'm thinking I'll just make a new branch off RPC-O, maybe a 14.23.1 tag, that points to the updated branch above, and then we'll just have rpc-upgrades leapfrog checkout the 14.23.1 tag instead.  It'll still be 14.23.0 but we won't have to worry about the missing artifacts that weren't created in 14.24.0.

**Comment by antonym** [comment]
If https://github.com/rcbops/openstack-ansible-openstack_hosts/pull/4 looks good for removing the linux-modules-extras stuff, then we can merge that.

Then we can recheck this PR and see if it skips those packages and checks out the right branches:

https://github.com/rcbops/rpc-upgrades/pull/369

**Comment by antonym** [comment]
Merged the fix for this in.
